# Generated by Django 4.2.6 on 2025-09-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedb',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicedb',
            name='description',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='servicedb',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicedb',
            name='servicename',
            field=models.CharField(max_length=200),
        ),
    ]
