# Generated by Django 4.2.6 on 2025-10-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontendcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pet_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Booked', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(max_length=20),
        ),
    ]
